### ISSUE TITLE
[bug #35498] misspelled in <util/setbaud.h>

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#515]
Fri 10 Feb 2012 02:13:55 AM CET

Hi,

in file <util/setbaud.h>,
maybe 'Output bacro from <util/setbaud.h>' in #define USE_2X is a mistake of 'macro' at the detailed description.

Best Regards,
Nao. Fujita

[file #27589: 35498.patch](https://savannah.nongnu.org/bugs/download.php?file_id=27589)

This issue was migrated from https://savannah.nongnu.org/bugs/?35498

**Comment by sprintersb** [comment]
Fixed by 71a127d277a0b237f964be8d6492e5d9c901d81d.
