### ISSUE TITLE
[bug #36168] LUFA BuildTests fails for xmega device - incorrect header files

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#522]
Fri 13 Apr 2012 05:01:37 PM CEST

See: [http://code.google.com/p/lufa-lib/issues/detail?id=47](https://savannah.nongnu.orghttp://code.google.com/p/lufa-lib/issues/detail?id=47)

This issue was migrated from https://savannah.nongnu.org/bugs/?36168

**Comment by sprintersb** [comment]
Closed.  This bug is not self-contining, and the external link went 404.
