### ISSUE TITLE
[bug #36609] pgmspace.h uses constraint "p"

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#528]
Fri 08 Jun 2012 10:23:28 AM CEST

include/avr/pgmspace.h uses constraint "p" in line 1030 (SVN trunk 2294).  This is plain wrong.

Sane constraint would be "i".

This issue was migrated from https://savannah.nongnu.org/bugs/?36609

**Comment by sprintersb** [comment]
Fixed by f6f785622c238cba2f726bfa30fe90a478bdd5ce.
