### ISSUE TITLE
[bug #36921] util/delay.h uses inline...

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#530]
Mon 23 Jul 2012 12:02:36 PM CEST

...instead of __inline or similar to make it work together with -std=c89

[file #27592: 36921.patch](https://savannah.nongnu.org/bugs/download.php?file_id=27592)

This issue was migrated from https://savannah.nongnu.org/bugs/?36921

**Comment by sprintersb** [comment]
Already fixed.
