### ISSUE TITLE
[bug #36970] FDEV_SETUP_STREAM doesn't work in C++

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#532]
Thu 26 Jul 2012 11:23:19 PM CEST

The FDEV_SETUP_STREAM macro defined in stdio.h only compiles for C99 because it uses designated initializers. The file attached shows a minimal program that shows the problem, adapted from the documentation here:
 [http://www.nongnu.org/avr-libc/user-manual/group__avr__stdio.html#stdio_without_malloc](https://savannah.nongnu.orghttp://www.nongnu.org/avr-libc/user-manual/group__avr__stdio.html#stdio_without_malloc)

However, when the program is compiled as C++, by giving the file a .cpp extension, the following errors appear:
$ avr-gcc fdevopenbug.cpp
fdevopenbug.cpp:6:24: sorry, unimplemented: non-trivial designated initializers not supported
fdevopenbug.cpp:6:24: sorry, unimplemented: non-trivial designated initializers not supported
fdevopenbug.cpp:6:24: sorry, unimplemented: non-trivial designated initializers not supported

This bug can be fixed by using a full initialization rather than the designated one.

This issue was migrated from https://savannah.nongnu.org/bugs/?36970

**Comment by sprintersb** [comment]
Dup of #898.
