### ISSUE TITLE
[bug #37825] math.h wrong code and not C90 compliant

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#544]
Thu 29 Nov 2012 12:06:19 AM CET

math.h uses inline which is not C90 (similar to bug 36921 with util/delay.h), here SVN 2264:
```
__ATTR_CONST__ static inline int isfinite (double __x)
{
unsigned char __exp;
 __asm__ (
"mov	%0, %C1		\n\t"
"lsl	%0		\n\t"
"mov	%0, %D1		\n\t"
"rol	%0		"
: "=r" (__exp)
: "r" (__x)	);
return __exp != 0xff;
}
```
`inline` is available in C99, not in C90. You can use `__inline__` or ` __inline` . Same applies to `copysign`.

Moreover, it is advisable to always inline this:

```
__ATTR_CONST__ static __inline__ __attribute__((__always_inline__))
int isfinite (const double __x)
```
This function might produce wrong code because the first instruction might clobber the input by overwriting %D1 . One solution is to early-clobber the output by means of &

This issue was migrated from https://savannah.nongnu.org/bugs/?37825

**Comment by sprintersb** [comment]
Fixed by 969b480d7215f92fa230f9e116fa750799c45f79.
