### ISSUE TITLE
[bug #37951] qsort will throw throws warning

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#549]
Tue 18 Dec 2012 02:07:20 PM CET

Building qsort (SVN 2303) throws following build warnings with avr-gcc-4.8-trunk:

avr-gcc -DHAVE_CONFIG_H -I. -I../../../../../source/avr-libc-1.8/avr/lib/avrxmega7 -I../../..  -I../../../../../source/avr-libc-1.8/common -I../../../../../source/avr-libc-1.8/include -I../../../include  -g -Wall -W -Wstrict-prototypes -mmcu=avrxmega7 -D__COMPILING_AVR_LIBC__ -Os -fno-jump-tables  -MT qsort.o -MD -MP -MF .deps/qsort.Tpo -c -o qsort.o ../../../../../source/avr-libc-1.8/libc/stdlib/qsort.c
../../../../../source/avr-libc-1.8/libc/stdlib/qsort.c: In function 'qsort':
../../../../../source/avr-libc-1.8/libc/stdlib/qsort.c:37:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
#define min(a, b) ((a) < (b) ? (a) : (b))
^
../../../../../source/avr-libc-1.8/libc/stdlib/qsort.c:140:6: note: in expansion of macro 'min'
r = min(pd - pc, pn - pd - es);
^
../../../../../source/avr-libc-1.8/libc/stdlib/qsort.c:37:36: warning: signed and unsigned type in conditional expression [-Wsign-compare]
#define min(a, b) ((a) < (b) ? (a) : (b))
^
../../../../../source/avr-libc-1.8/libc/stdlib/qsort.c:140:6: note: in expansion of macro 'min'
r = min(pd - pc, pn - pd - es);
^
../../../../../source/avr-libc-1.8/libc/stdlib/qsort.c:142:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
if ((r = pb - pa) > es)
^
../../../../../source/avr-libc-1.8/libc/stdlib/qsort.c:144:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
if ((r = pd - pc) > es) {
^

This issue was migrated from https://savannah.nongnu.org/bugs/?37951

**Comment by sprintersb** [comment]
Fixed by https://github.com/avrdudes/avr-libc/commit/f3e965240cc600ed57e3ef00bdca76ae5fa2dff0.
