### ISSUE TITLE
[bug #38025] Documentation misses memcpy_P et at.

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#551]
Sat 05 Jan 2013 08:06:29 PM CET

The documentation misses memcpy_P et at.  Only the far variants are documented.

This issue was migrated from https://savannah.nongnu.org/bugs/?38025

**Comment by sprintersb** [comment]
Fixed by 53ebddb186853fe1e9f43ba5c0edf5d8f148a21e.
