### ISSUE TITLE
[bug #38037] "Building and Installing" needs round-up

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#552]
Mon 07 Jan 2013 07:17:52 PM CET

The "Building and Installing under Linux, FreeBSD, and Others" documentation [1] needs some fixes:

1)
"Installing GCC" states in [2]:
"First, we **highly** recommend that GCC be built into a
separate directory from the sources which does not reside
within the source tree. [...] building where srcdir == objdir
should still work, but doesn't get extensive testing;
building where objdir is a subdirectory of srcdir is
not supported."

Nevertheless [1] uses ../configure, i.e. objdir is a subdirectory of srcdir.

2)
Depending on its version, GCC needs several prerequisites: GMP, MPFR, MPC.  The recommended way to get them is to "cd $(srcdir)" and then to run ./contrib/download_prerequisites and to do an in-tree build with these prerequisites.  This ensures the right versions of the prerequisites are used and that they are configured in sync with GCC, cf. [3]

3) GCC configure should be performed with --with-avrlibc, cf. [2] and see [4] for reasoning.

4) Recent versions of GCC are distributed as one chunk, there is no gcc-core etc. any more.

5) Binutils need not to be in the PATH as GCC is being built provided both are configured with the same prefix.

6) With Linux, Binutils and GCC for MS windows can be built as easily as the tools for Linux:  Just configure with, say, --target=i386-mingw32 --build=x86-linux-gnu.  This requires working avr-gcc (you already built it as described) and i386-ming32-gcc cross-compilers.  The rest of the build process is the same, including the in-tree builds of the prerequisites.

[1] [http://nongnu.org/avr-libc/user-manual/install_tools.html](https://savannah.nongnu.orghttp://nongnu.org/avr-libc/user-manual/install_tools.html)
[2] [http://gcc.gnu.org/install/configure.html](https://savannah.nongnu.orghttp://gcc.gnu.org/install/configure.html)
[3] [http://gcc.gnu.org/wiki/InstallingGCC](https://savannah.nongnu.orghttp://gcc.gnu.org/wiki/InstallingGCC)
[4] [http://gcc.gnu.org/PR54461](https://savannah.nongnu.orghttp://gcc.gnu.org/PR54461)

This issue was migrated from https://savannah.nongnu.org/bugs/?38037

**Comment by sprintersb** [comment]
Done. All the points have been addressed by now.
