### ISSUE TITLE
[bug #38904] /usr/avr/include/util/delay.h:248:10: note: '__ticks' was declared here

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#561]
Mon 06 May 2013 02:22:16 PM CEST

Changes from 2013-05-03 introduce bug in:
/usr/avr/include/util/delay.h
With gcc-4.8 I get:
```
usr/avr/include/util/delay_basic.h:83:2: error: '__ticks' may be used
uninitialized in this function [-Werror=maybe-uninitialized]
 __asm__ volatile (
^
/usr/avr/include/util/delay.h:248:10: note: '__ticks' was declared here
uint8_t __ticks;
^
lto1: all warnings being treated as errors
make[1]: *** [/tmp/ccVIU3hR.ltrans8.ltrans.o] Błąd 1
```

Maybe there is an error in /usr/avr/include/util/delay.h ?
_delay_loop_1(__ticks) should be run always or it should be in braces with:
```
else    {
__ticks = (uint8_t)__tmp;
_delay_loop_1(__ticks);
}
```
This issue was migrated from https://savannah.nongnu.org/bugs/?38904

**Comment by sprintersb** [comment]
No more reproducible.
