### ISSUE TITLE
[bug #39297] <avr/interrupt.h> documentation should mention SIG* is now poisoned

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#567]
Thu 20 Jun 2013 11:35:27 AM CEST

Now that the AVR-LibC headers for devices that still have SIG_* names defined also uses #poison for each the manual should be updated to reflect this and point out that it's no longer the case that SIG_* is simply deprecated but is effectively unusable unless `__AVR_LIBC_DEPRECATED_ENABLE__` is defined.

This issue was migrated from https://savannah.nongnu.org/bugs/?39297

**Comment by sprintersb** [comment]
Fixed by 413327fe4321e8a44fbf7d22014ce39650c6837f.
