### ISSUE TITLE
[bug #40595] iotn2313a.h: wrong fuses definitions for High Fuse Byte

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#578]
Sat 16 Nov 2013 11:19:41 AM CET

High Fuse Byte symbols in iotn2313a.h are defined in a wrong order.

[file #30814: iotn4313.h](https://savannah.nongnu.org/bugs/download.php?file_id=30814)
[file #30813: iotn2313a.h](https://savannah.nongnu.org/bugs/download.php?file_id=30813)
[file #30812: iotn2313a_4313_h.patch](https://savannah.nongnu.org/bugs/download.php?file_id=30812)

This issue was migrated from https://savannah.nongnu.org/bugs/?40595

**Comment by avrs-admin** [comment]
pozzugno <pozzugno>
Sun 17 Nov 2013 03:31:14 PM CET

The same problem on iotn4313.h

**Comment by sprintersb** [comment]
Fixed by 1950e6971cf3ea22edfa3640b88a0d1db9fd449c.
