### ISSUE TITLE
[bug #41502] TWI Library changes TIMSK2

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#581]
Fri 07 Feb 2014 02:01:25 PM CET

TWI_Init changes the Timer/Counter Interrupt Mask Register of Timer 2 (TIMSK2) as you can see here:

TWI_Init (void)
{
// Port Setup
DDRC &= ~((1 << PC0)|(1 << PC1));
PORTC |= (1 << PC0)|(1 << PC1);

// Setup TWI Speed to 400kHZ (TWPS = 1)
TWBR = 3;

// Using TIMER2 to detect timeout
TCCR2B = (7 << CS20);
TIMSK2 = (1 << OCIE2A);

OCR2A = 125;

// Interrupts REQUIRED!
sei();
}

[file #30481: twi.h](https://savannah.nongnu.org/bugs/download.php?file_id=30481)
[file #30480: twi.c](https://savannah.nongnu.org/bugs/download.php?file_id=30480)

This issue was migrated from https://savannah.nongnu.org/bugs/?41502

**Comment by sprintersb** [comment]
I don't get what you are talking about.  There's no `TWI_Init` function in the entire library, and also no file `twi.c`.
