### ISSUE TITLE
[bug #41519] wrong SPM_PAGESIZE definition in iotn[48]8.h

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#582]
Sun 09 Feb 2014 04:42:50 AM CET

line 717 include/avr/iotn88.h defines SPM_PAGESIZE as 32
correct value is 64 as per datasheet section 21.1.
same for iotn48.h

[file #30810: iotn48_88_h.patch](https://savannah.nongnu.org/bugs/download.php?file_id=30810)
[file #30809: iotn88.h](https://savannah.nongnu.org/bugs/download.php?file_id=30809)
[file #30808: iotn48.h](https://savannah.nongnu.org/bugs/download.php?file_id=30808)

This issue was migrated from https://savannah.nongnu.org/bugs/?41519

**Comment by sprintersb** [comment]
Fixed by e71b76d1b7c19c623cfc8851206193958f44b711.
