### ISSUE TITLE
[bug #42085] HFUSE_DEFAULT not defined for iotn84.h

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#588]
Thu 10 Apr 2014 03:57:13 AM CEST

#define FUSE_HFUSE_DEFAULT (FUSE_SPIEN)
should be:
#define HFUSE_DEFAULT (FUSE_SPIEN)

This issue was migrated from https://savannah.nongnu.org/bugs/?42085

**Comment by sprintersb** [comment]
Fixed by 2dde278e1149ce1491a94cc2262038396a964951.
