### ISSUE TITLE
[bug #43204] _PROTECTED_WRITE Does not work in the register of the address 0x0100 or more

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#596]
Fri 12 Sep 2014 06:04:32 AM CEST

ex:_PROTECTED_WRITE(NVM_CTRLA, NVM_CMDEX_bm);

I was not able to compile this code.
The cause was that the address of NVM_CTRLA is 0x01CB.

This issue was migrated from https://savannah.nongnu.org/bugs/?43204

**Comment by sprintersb** [comment]
Fixed by e68e766fb63f66f1669ca0a305465c042bdf307f.
