### ISSUE TITLE
[bug #44306] Redundancy between rand_r() and do_rand()

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#604]
Thu 19 Feb 2015 10:30:50 AM CET

In libc/stdlib/rand.c, the functions rand_r() and do_rand() are
redundant relative to each other. I suggest the following:

- remove rand_r(),
- remove the "static" attribute from do_rand(),
- rename do_rand() -> rand_r(),
- have rand() call rand_r() instead of do_rand().

This should save 4 bytes of flash on every program using rand() or
rand_r(). It should also save 2 bytes of stack and 7 clock cycles on
calls to rand_r(), more if **_AVR_3_BYTE_PC_**.

Same thing for random_r() and do_random() in libc/stdlib/random.c.

This issue was migrated from https://savannah.nongnu.org/bugs/?44306

**Comment by sprintersb** [comment]
Fixed by cdf3dc1875d3e98cc120615538c52e4250c1df95 (for `rand` and `rand_r`).

`random` and `random_r` use the same code already since the initial commit cdf3dc1875d3e98cc120615538c52e4250c1df95.
