### ISSUE TITLE
[bug #44994] example of printf("Hello, world!\n") in documentation is errenuous

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#614]
Sat 02 May 2015 08:28:35 AM CEST

gcc optimizes this to puts("Hello, world!"), making the documentation inaccurate.

This issue was migrated from https://savannah.nongnu.org/bugs/?44994

**Comment by avrs-admin** [comment]
Joerg Wunsch <joerg_wunsch>
Sat 02 May 2015 09:00:26 AM CEST

What exactly is made "innacurate" by that?

**Comment by sprintersb** [comment]
The documentation is fine.  What the compiler does is to implement `printf("Hello, world!\n")` according to the language standard.  That the abstract machine behaves the same for a different construct doesn't render the documentation invalid. Closed thusly.
