### ISSUE TITLE
[bug #45698] memory sections documentation unclear or misleading

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#624]
Wed 05 Aug 2015 07:30:18 AM CEST

[http://www.nongnu.org/avr-libc/user-manual/mem_sections.html](http://www.nongnu.org/avr-libc/user-manual/mem_sections.html)

says:
.init2:
In C programs, weakly bound to initialize the stack, and to clear zero_reg (r1).

As far as I can tell, you can have weak symbols (like __init is defined as weak in crt1.o) but you can't have weak sections.

This issue was migrated from https://savannah.nongnu.org/bugs/?45698

**Comment by sprintersb** [comment]
The stack pointer `SP` is initialized with the value of (weak) symbol `__stack`.  Hence you can re-define symbol `__stack` to adjust the initial `SP` value: `-Wl,--defsym,__stack=<value>`.
