### ISSUE TITLE
[bug #47922] avr/power.h missing support for ATtiny841/441

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#632]
Sat 14 May 2016 07:25:12 PM CEST

avr/power.h is missing support for ATtiny841 and ATtiny441.

Atmel Studio 7.0.790 included modified version of avr-libc 1.8.0 with support added.

Included two files from the Atmel modified avr-libc 1.8.0.

power.h_addition_attinyX41.h includes only the added part for ATtiny841/441 support.
power.h_atmel_modified_1.8.0.h is the whole file included with Atmel Studio 7.0.790, which is based on avr-libc 1.8.0.

[file #37157: power.h_addition_attinyX41.h](https://savannah.nongnu.org/bugs/download.php?file_id=37157)
[file #37158: power.h_atmel_modified_1.8.0.h](https://savannah.nongnu.org/bugs/download.php?file_id=37158)

This issue was migrated from https://savannah.nongnu.org/bugs/?47922

**Comment by sprintersb** [comment]
Applied as 7deac7caa836b020986c1749c052b169ebaf7724.
