### ISSUE TITLE
[bug #49565] at43usb320 in wrong multilib set

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#641]
Wed 09 Nov 2016 03:03:26 PM CET

Mentioned device is filed in avr31 which is for "old" 180KiB devices, but AT43usb320 has only support for 64 KiB program memory.  In particular, it has no support for ELPM.

This issue is also present in avr-gcc, cf. [http://gcc.gnu.org/PR78275](https://savannah.nongnu.orghttp://gcc.gnu.org/PR78275)

This issue was migrated from https://savannah.nongnu.org/bugs/?49565

**Comment by sprintersb** [comment]
From multilib patch f4ec4b741bc608f0afc471734afa097e905fed9b on, this is a GCC (or device pack) issue.
