### ISSUE TITLE
[bug #49688] wdt_enable() should get an entry on avr/wdt.h documentation page

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#644]
Thu 24 Nov 2016 12:30:06 AM CET

It is mentioned under WDTO_15MS #define but it doesn't get an entry of it's own, which is inconsistent with other pages and with the fact that wdt_reset() does get it's own entry.

It would be nice if it got described if wdt_enable() implicitly does wdt_reset() or not.

This issue was migrated from https://savannah.nongnu.org/bugs/?49688

**Comment by sprintersb** [comment]
Fixed by https://github.com/avrdudes/avr-libc/commit/8129367262ed26b75940965a8532a86f1a45e2b7
