### ISSUE TITLE
[bug #55703] Confusion in function descriptions

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#665]
Wed 13 Feb 2019 05:35:17 AM CET

Re: page 168 in the avr-libc-user-manual-2.0.0.pdf, 23.11.3.26

The function reads: char * strncat ( char * dest, const char * src, size_t len ) and the description states "... only the first n characters of src ...".

The description should state "... only the first len characters of src ..."

Minor issue, but I notice the edit has be done in 23.11.3.25 and should probably be done in 23.11.3.27 thru 29, possibly others as well.

This issue was migrated from https://savannah.nongnu.org/bugs/?55703

**Comment by sprintersb** [comment]
Fixed by https://github.com/avrdudes/avr-libc/commit/fcde06683b0fa2de6a5c790b9599fef8fff47e2d.
