### ISSUE TITLE
[bug #56093] Wrong constraint in pgmspace.h::pgm_get_far_address

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#666]
Sun 07 Apr 2019 03:00:58 PM CEST

Macro pgm_get_far_address() from avr/pgmspace.h has a wrong constraint for operand %1: Is must be "ni" (known at compile-time (n) or known ar assembly time or later (i)) instead of "p".

Moreover, the asm is not volatile, hence the "volatile" can be dropped.

The "tmp" should also be recplaced by an identifier from implementation space like __tmp.

Last not least, the macro should come with "extension" so that it will work in strict C mode (and not only with GNU-C which valued blocks are).

Putting everything together, the macro should read

```
#define pgm_get_far_address(var)                      \
(__extension__({                                      \
uint_farptr_t __tmp;                              \
\
__asm__ (                                         \
"ldi    %A0, lo8(%1)"           "\n\t"    \
"ldi    %B0, hi8(%1)"           "\n\t"    \
"ldi    %C0, hh8(%1)"           "\n\t"    \
"clr    %D0"                    "\n\t"    \
: "=d" (__tmp)                                \
: "ni" (&(var))                               \
);                                                \
__tmp;                                            \
}))

```

This issue was migrated from https://savannah.nongnu.org/bugs/?56093

**Comment by sprintersb** [comment]
Fixed by f6f785622c238cba2f726bfa30fe90a478bdd5ce.
