### ISSUE TITLE
[bug #56278] ATmega328PB

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#667]
Mon 06 May 2019 09:01:13 PM CEST

in iom328pb.h

DIDR0 is missing ADC6D and ADC7D

This issue was migrated from https://savannah.nongnu.org/bugs/?56278

**Comment by sprintersb** [comment]
ATmega328PB support has been added as #879, and `DIDR0` has the `ADC6D` and `ADC7D` defines.
