### ISSUE TITLE
[bug #56650] https://www.nongnu.org/avr-libc/user-manual/install_tools.html

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#669]
Sun 21 Jul 2019 03:30:36 AM CEST

Hello All,

Just a small error in the instructions on how to build avr-libc with debugging symbols.  The web page (in the summary) says to pass --with-debug-info this is incorrect.  We must pass --enable-debug-info instead.

Chris

This issue was migrated from https://savannah.nongnu.org/bugs/?56650

**Comment by sprintersb** [comment]
This was fixed in 5fb785f605eadc57df8a909488563eab6
