### ISSUE TITLE
[bug #57154] iom1284p.h: typo of OCR1BL0:OCR1BL7, OCR1BH0:OCR1BH7, OCR3BL0:OCR3BL7 and OCR3AH0:OCR3AH7

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#672]
Sat 02 Nov 2019 05:34:47 PM CET

the registers OCR1BL0:OCR1BL7, OCR1BH0:OCR1BH7, OCR3BL0:OCR3BL7 and OCR3AH0:OCR3AH7 are missing from the header file and where they should be defined there are the registers with the names **A**n instead of **B**n defined. (lines 693-710 and 802-819)

I'm not sure if the same code was copy-pasted to/from some other header files because I have only looked at this file so far. I noticed this because it redefined an already existing define for all the A values with the same value.

What I also noticed but where I don't know if it's an issue: OCR2_0:OCR2_7 is also defined twice. (once below OCR2A and once below OCR2B) I'm not sure if this was intended because all other memory addresses usually have a different naming and in the data sheet in 17.11.4 OCR2A – Output Compare Register A and 17.11.5 OCR2A – Output Compare Register B they are named OCR2A[7:0] and OCR2B[7:0] respectively instead of OCR2[7:0] (though changing these might break programs relying on those defines)

I have also attached a patch (diff -rupN) which fixes the naming of the macros mentioned in the bug title here but not the OCR2_n macros.

[file #47780: patch.txt](https://savannah.nongnu.org/bugs/download.php?file_id=47780)

This issue was migrated from https://savannah.nongnu.org/bugs/?57154

**Comment by sprintersb** [comment]
Applied as https://github.com/avrdudes/avr-libc/commit/bf4f147ab0ff413cea53fd8288587bb212ef2953.
