### ISSUE TITLE
[bug #58699] Add support for Atmega324PB

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#676]
Sat 04 Jul 2020 09:31:30 AM CEST

Attached here is a patch to add support for Atmega324PB (can be found on Atmega324pb Explain PRO SDK board).

[file #49421: 0001-Add-support-for-atmega324pb.patch](https://savannah.nongnu.org/bugs/download.php?file_id=49421)

This issue was migrated from https://savannah.nongnu.org/bugs/?58699

**Comment by sprintersb** [comment]
Added in e1ea38fa0a40050c5fddd09bc17d20f628f550d8.
