### ISSUE TITLE
[bug #59644] Typos in include/util/atomic.h comments

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#680]
Wed 09 Dec 2020 04:02:48 PM CET

The attached patch fixes a number of typos.

[file #50429: avr.patch](https://savannah.nongnu.org/bugs/download.php?file_id=50429)

This issue was migrated from https://savannah.nongnu.org/bugs/?59644

**Comment by sprintersb** [comment]
Applied as https://github.com/avrdudes/avr-libc/commit/229a9beabde7e30af2e19342e9e312cd047cda21.
