### ISSUE TITLE
[bug #60662] Xmega.h is prepared for Doxygen but not added to doxygen.config.in

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#682]
Mon 24 May 2021 11:43:16 AM CEST

Now that the recently added AVR-0/AVR-1/AVR-DB mean there are many more "Xmega"" being used, there is increasing requirement for _PROTECTED_WRITE() to write CCP protected registers.

Clearly the avr/include/xmega.h header has been prepared for Doxygen but it does not appear in the published documentation. This is simply (I believe) because it has not been listed around line 774 in avr-libc/doc/api/doxygen.config.in where the other ("main") files in avr/include are listed. Suggest that

@top_srcdir@/include/time.h \
+ @top_srcdir@/include/xmega.h \

an additional line be added after "time.h" to also list "xmega.h"

This issue was migrated from https://savannah.nongnu.org/bugs/?60662

**Comment by sprintersb** [comment]
Fixed by c79a2af5321088d740ac192ef9e7e5b8d1154264.
