### ISSUE TITLE
[bug #61102] Missing support for ATmega324PA in header file avr/power.h

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#684]
Wed 01 Sep 2021 01:22:15 PM CEST

Missing support for ATmega324PA in header file avr/power.h

In the header file "avr/power.h" some declarations like
clock_prescale_set() are not declared for ATmega324PA.

Patch attached.

[file #51858: patch-include_avr_power.h](https://savannah.nongnu.org/bugs/download.php?file_id=51858)

This issue was migrated from https://savannah.nongnu.org/bugs/?61102

**Comment by sprintersb** [comment]
Fixed by https://github.com/avrdudes/avr-libc/commit/d7b2eca301040dd3c9d6cea93f8fd780d16b0525.
