### ISSUE TITLE
[patch #9968] Update __mul[hs]i_const_10 functions to detect them as function in the ELF object

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#830]
Wed 26 Aug 2020 11:11:13 AM CEST

The __mul[hs]i_const_10 functions are defined in assembly, but these symbols' types are unknown ("NOTYPE") in ELF object.

Example:
$ avr-readelf -s ~/install/avr/lib/avrxmega3/libc.a | grep "_const_10"
6: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND __mulhi_const_10
6: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND __mulsi_const_10
5: 00000000     0 NOTYPE  GLOBAL DEFAULT    4 __mulsi_const_10
5: 00000000     0 NOTYPE  GLOBAL DEFAULT    4 __mulhi_const_10

The attached patch updates these functions type and also adds .size attribute.
Output after applying this patch:
$ avr-readelf -s ~/install/avr/lib/avrxmega3/libc.a | grep "_const_10"
6: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND __mulhi_const_10
6: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND __mulsi_const_10
5: 00000000    42 FUNC    GLOBAL DEFAULT    4 __mulsi_const_10
5: 00000000    16 FUNC    GLOBAL DEFAULT    4 __mulhi_const_10

[file #49708: mulhi_si_const_10.patch](https://savannah.nongnu.org/patch/download.php?file_id=49708)

This issue was migrated from https://savannah.nongnu.org/patch/?9968

**Comment by sprintersb** [comment]
Fixed by 004128ec09a38cad22040dfcc7e2b3211ac5a7c4.
