### ISSUE TITLE
Lock interface for newer AVR8X parts redefines LOCKBITS_DEFAULT

### ISSUE THREAD

**Issue by stefanrueger** [avrdudes/avr-libc#880]
The newer AVR8X family parts have a different lock interface.

Unconditionally including `avr/lock.h` in `io.h` leads to `LOCKBITS_DEFAULT` value of `0xC5` being re-defined with `0xFF`.

Fun fact: of the 34 AVR8X parts supported in avr-gcc 11.2.0 `attiny3214.h` fails to `#define LOCKBITS_DEFAULT (0xC5)` though it probably should.

**Comment by sprintersb** [comment]
Fixed by https://github.com/avrdudes/avr-libc/commit/c6b72b4c9b8dd2a8b9d05ae0a9acf9e91a3b28d5.
