### ISSUE TITLE
Error 0x800704B0: The specified device name is invalid.

### ISSUE THREAD

**Issue by mianqi2016** [avrdudes/avr-libc#889]
I downloaded the zip file and extracted it on Windows 10, till 99% procession, it was prompted this:
![Untitled](https://user-images.githubusercontent.com/22947586/178697821-62681c72-8a03-43a3-a828-2955ca989814.png)

**Comment by dl8dtl** [comment]
Well, blame Windows for that nonsense. It really does not make any sense to me to consider a file named "aux.c" as a possible candidate for a peripheral device.

Strange that you're the first one to stumble across that – that file has been sitting there for almost 10 years now.

Surely, we can rename that in a future release. As the file is only part of the testbench, you can safely skip it when extracting the archive.

**Comment by ckormanyos** [comment]
Hi @sprintersb thank you for resolving this. I just cloned on Windows and worked with the repo a bit. I can confirm, at least on my clone, this fix works. The new filename is `xua.c`.
