### ISSUE TITLE
Rename file "aux.c" because it is a reserved filename on Windows

### ISSUE THREAD

**Issue by fvilante** [avrdudes/avr-libc#897]
**Improve Multi-Platform Support**

The file `'tests/simulate/time/aux.c'` use a [reserved filename](https://www.helpndoc.com/documentation/html/Windowsreservedfilenames.html) on Microsoft Windows systems.

Therefore you will experience an error when cloning this repository on Windows.

This error also propagates to downstream users of other languages like in this case [rust_avr_libc](https://github.com/avr-rust/libc). The building tools also does not work because that.

Just renaming the filename will solve the problem and make the library platform agnostic.

related: #889 

---
```powershell
╰─❯ git clone https://github.com/avrdudes/avr-libc.git
Cloning into 'avr-libc'...
remote: Enumerating objects: 22589, done.
remote: Counting objects: 100% (576/576), done.
remote: Compressing objects: 100% (115/115), done.
remote: Total 22589 (delta 488), reused 536 (delta 461), pack-reused 22013
Receiving objects: 100% (22589/22589), 9.85 MiB | 5.59 MiB/s, done.
Resolving deltas: 100% (18329/18329), done.
error: invalid path 'tests/simulate/time/aux.c'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by sprintersb** [comment]
Closed as dup of #889.
