### ISSUE TITLE
SPM control register bit 3 name change with ATtiny828 prevents from using fuse bits API

### ISSUE THREAD

**Issue by 3-14152898** [avrdudes/avr-libc#949]
The ATtiny828 does have the `SPMCSR` special register but its third bit is named differently, i.e. `RWFLB` instead of `BLBSET` or `RFLB`. Consequently that prevents function (macro) `boot_lock_fuse_bits_get` from compiling.

I'm adding a patch to `avr/boot.h`  to fix that issue... (well, if Github becomes smart enough to eventually get that a file ending with `.patch` is actually... a patch!)

EDIT: Finally! See [patch.zip](https://github.com/avrdudes/avr-libc/files/14378192/patch.zip)

Cheers.

**Comment by sprintersb** [comment]
Fixed by https://github.com/avrdudes/avr-libc/commit/52e7b75ef4820f8fe5166f5774021a557ac1b77c
