### ISSUE TITLE
Current web documentation has trashed code indentations

### ISSUE THREAD

**Issue by sprintersb** [avrdudes/avr-libc#950]
Due to a Doxygen bug introduced in v1.8.1.2, the indentations in `\code` regions are gone.

See for example the online [FAQ](https://www.nongnu.org/avr-libc/user-manual/FAQ.html#faq_flashstrings) which is generated with Doxygen v1.8.7 (as of 2024-03-17).

See also [stackoverflow: Doxygen: `\code` tag kills indentation](https://stackoverflow.com/questions/11190838/doxygen-code-tag-kills-indentation).  A comment says that the bug is fixed in v1.8.7 (which it obviously is not...)

My local Doxygen version is v1.9.1 and the indentations work as expected.

**Note**: Other parts of the web documentation work as they were generated with v1.8.14, so just re-make all of the docs with that version or newer.

**Comment by dl8dtl** [comment]
My local version is 1.9.6. Guess I could try rebuilding everything …

**Comment by sprintersb** [comment]
Re-building would also fix #597. (Though https://www.nongnu.org/avr-libc/user-manual/using_tools.html is pretty much outdated).

**Comment by sprintersb** [comment]
Fixed by using an updated Doxygen version (v1.9.1).
